import { chromium } from "playwright";
const b = await chromium.launch();
const page = await (await b.newContext({ viewport: { width: 1162, height: 909 } })).newPage();
const errs = []; page.on("pageerror", (e) => errs.push(e.message));
const line = (k, v) => console.log("  " + String(k).padEnd(40) + v);
await page.goto("http://localhost:3000/probe.html", { waitUntil: "networkidle" });
await page.waitForSelector("#plain input", { timeout: 15000 });
await page.waitForTimeout(1200);
line("ค่าที่แสดง (หลัง lazy โหลดเสร็จ)", await page.inputValue("#plain input"));
line("readOnly (ถ้ายังเป็น fallback จะ true)", await page.$eval("#plain input", (e) => e.readOnly));
await page.click("#plain input");
await page.waitForTimeout(1200);
line("ปฏิทินเปิดไหม", (await page.$(".MuiCalendarPicker-root")) ? "เปิด" : "ไม่เปิด <<<");
line("หัวปฏิทิน", (await page.textContent(".MuiPickersCalendarHeader-label").catch(() => "-")) || "-");
await page.keyboard.press("Escape"); await page.waitForTimeout(400);

await page.click("#open-addevent");
await page.waitForTimeout(2800);
line("ฟอร์ม AddEvent เปิด", (await page.$(".swal2-popup")) ? "ใช่" : "ไม่");
const h = await page.evaluate(() => { const d = document.querySelector(".swal2-popup .MuiOutlinedInput-root"); return d ? Math.round(d.getBoundingClientRect().height) : null; });
line("ความสูงช่องวันที่ในฟอร์ม", h + " px");
await page.click(".swal2-popup .MuiInputBase-input:visible").catch(() => {});
await page.waitForTimeout(1300);
line("ปฏิทินในฟอร์มเปิดไหม", (await page.$(".MuiCalendarPicker-root")) ? "เปิด" : "ไม่เปิด <<<");
line("errors", errs.length ? errs.slice(0,2).join(" | ").slice(0,140) : "none");
await b.close();
